### ISSUE TITLE
您好，我想咨询您一个关于jekyll的问题

### ISSUE THREAD

**Issue by Joozo** [pizn/pizn.github.com#4]
具体情况是这样的，我下载一个jekyll 主题，然后build，原有的文章、内容可以build。我自己新建的文章为什么不能build至_site文件夹中呢？望解惑！

**Comment by pizn** [comment]
有地址可以看么？单看问题不知道是啥

**Comment by Joozo** [comment]
aliccc.com

**Comment by Joozo** [comment]
http://aliccc.com
